import Head from "next/head";
import SearchIcon from "../assets/Search_Icon.svg";
import FilterIcon from "../assets/Filter_Icon.svg";
import RecentExperiences from "../components/recent-experiences";
import PopularCategories from "../components/popular-categories";
const Home = () => {
  return (
    <div>
      <Head>
        <title>Reg Email</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="p-5 bg-white">
        <div className="header flex justify-between items-center">
          <div className="search-field relative w-4/5">
            <SearchIcon className="pointer-events-none w-8 h-8 absolute top-7 transform -translate-y-1/2 left-3" />
            <input
              type="text"
              className="rounded-lg w-full border-0 bg-slate-100 pl-10"
              placeholder="Search experiences"
            />
          </div>
          <div className="cursor-pointer">
            <FilterIcon />
          </div>
        </div>
        <div className="mt-5">
          <RecentExperiences />
        </div>
        <div className="mt-5">
          <PopularCategories />
        </div>
      </div>
    </div>
  );
};

export default Home;
